import os

API_KEY = os.environ.get("VERBIX_API_KEY", "6153a464-b4f0-11ed-9ece-ee3761609078")  # API key used on the website

SUPPORTED_LANGS={
    "spa": "Spanish",
    "por": "Portuguese",
    "fra": "French",
    "ita": "Italian",
    "ron": "Romanian",
    "glg": "Galician",
    "cat": "Catalan",
    "oci": "Occitan",
    "lat": "Latin",
    "fin": "Finnish",
    "got": "Gothic",
    "eng": "English",
    "swe": "Swedish",
    "deu": "German",
    "ang": "Old English",
    "nld": "Dutch",
    "nob": "Norwegian (bokmål)",
    "dan": "Danish",
    "isl": "Icelandic",
    "tur": "Turkish",
    "pdt": "Plautdietsch",
    "jpn": "Japanese",
    "nno": "Norwegian (Nynorsk)",
    "ltz": "Luxembourgish",
    "kal": "Greenlandic",
    "ell": "Greek",
    "hun": "Hungarian",
    "rus": "Russian",
    "ukr": "Ukrainian",
    "lit": "Lithuanian",
    "tib": "Tibetan",
    "bul": "Bulgarian",
    "ind": "Indonesian",
    "dlm": "Dalmatian",
    "epo": "Esperanto",
    "est": "Estonian",
    "kor": "Korean",
    "mkd": "Macedonian",
    "tha": "Thai",
}